### ISSUE TITLE
Filename in statusline

### ISSUE THREAD

**Issue by arminfro** [Avimitin/nerd-galaxyline#1]
Hey there,

thank you for this plugin! I really like it, the only thing I'm missing is the (expanded) filename in the statusline.

I've forked your project and [added this feature](https://github.com/arminfro/nerd-galaxyline/commit/d9b4ed36543bbb97a8ed684861a54ef20afb5272). 

If you like, I can open a PR, otherwise I'll just close the issue :v:

**Comment by Avimitin** [comment]
Actually, I have some changed on the status line which has not been uploaded yet. So feel free to create a new PR but please create a new branch. I will merge it into the master branch later. Thanks a lot for your contribution!

**Comment by arminfro** [comment]
I made a new branch called `add-filename` on my repo. For the target branch, I was only able to choose your `master` branch.

**Comment by Avimitin** [comment]
In my local modify, I changed the line background color to #16191D. Do you accept this change? Or maybe I should let it be an option?

**Comment by Avimitin** [comment]
![图片](https://user-images.githubusercontent.com/30021675/126947252-32fc64c6-7253-4c4a-a89d-36766226544e.png)

I found that your change can replace the `FileTypeName` valuable. That's how it looks like after merged.

**Comment by arminfro** [comment]
The background color change is fine for me. I'm using [zephyr-nvim](https://github.com/glepnir/zephyr-nvim), that fits quite well.

**Comment by Avimitin** [comment]
I've pushed my local change to the repository, you can have a try on it. Thank's for your support.
