### ISSUE TITLE
local mode_color contains undefined color

### ISSUE THREAD

**Issue by mstcl** [Avimitin/nerd-galaxyline#3]
Some vague errors were returned when I entered Replace mode. I noticed that  `R = colors.violet,Rv = colors.violet` is present, but `colors.violet` is not defined, perhaps you meant purple or magenta?

**Comment by Avimitin** [comment]
My bad, I forgot to replace the value after I deleted it.

**Comment by Avimitin** [comment]
Fixed in https://github.com/Avimitin/nerd-galaxyline/commit/58423af9acbf88c4f78359c485856a75d5b9e074
