### ISSUE TITLE
Updating nerd-galaxyline to support NTBBloodbath/galaxyline.nvim?

### ISSUE THREAD

**Issue by ristillu** [Avimitin/nerd-galaxyline#5]
I was using your excellent plugin along with glepnir's galaxyline when it suddenly stopped working on my nightly neovim builds. The errors I was getting made neovim unusuable. In searching for what might have changed I came across this thread: https://github.com/glepnir/galaxyline.nvim/issues/222
and therefore switched to the NTBBloodbath/galaxyline.nvim fork, but it appears there are enough changes to make it not plug'n'play with your plugin. Do you have any thoughts to modifying your plugin to support NTBBloodbath's?

**Comment by Avimitin** [comment]
I have a fork version of the original galaxyline. You can have a try on this: https://github.com/Avimitin/galaxyline.nvim. I only made some trivial changes that didn't affect the code.

I have no plan to try on others statusline. Galaxyline fit my needs so well. Sorry about that.
